### PR TITLE
Brizy page builder compatibility

### PR DESCRIPTION
**Pull request by kprajapatii**

### CODE REVIEW

**Comment by ViorelEremia** [comment]
Hi @kprajapatii, 
could you add that condition like here?

```
if (
	( ( function_exists( 'et_divi_load_scripts_styles' ) || function_exists( 'dbp_filter_bfb_enabled' ) ) && ! empty( $_REQUEST['et_fb'] ) && ! empty( $_REQUEST['et_bfb'] ) ) // Divi
	||
	(
		class_exists( 'Brizy_Editor' ) &&
		(
			( isset( $_GET[ Brizy_Editor::prefix( '-edit' ) ] ) || isset( $_GET[ Brizy_Editor::prefix( '-edit-iframe' ) ] ) ) ||
			Brizy_Editor_Entity::isBrizyEnabled( geodir_search_page_id() )
		)
	) // Brizy
) {
```
will this create any trouble in the frontend if those variables won't be set to false in the frontend only the page is created with brizy.

**Comment by kprajapatii** [comment]
Fixes #1557 https://github.com/AyeCode/geodirectory/commit/2697829aa6c4b004ca5b6d3b3210621684fc8baa

**Comment by kprajapatii** [comment]
Hi @ViorelEremia,

Added https://github.com/AyeCode/geodirectory/pull/1648/commits/c9d02117cca573e9019115c4addc0e9eacd7802d

**Comment by ViorelEremia** [comment]
Thanks @kprajapatii 
everything looks ok.

**Comment by kprajapatii** [comment]
Fixes #1588 https://github.com/AyeCode/geodirectory/pull/1648/commits/36ea16ba8ab56616fbc58f982b7896ac8bc5d589

**Pull request merged**
