### PR TITLE
Rank Math SEO plugin's compatibility

### PR DESCRIPTION
**Pull request by MyThemeShop**
This PR makes the plugin compatible with [Rank Math SEO](https://wordpress.org/plugins/seo-by-rank-math/) plugin so, both the plugins can play along nicely without interfering with each other.

### CODE REVIEW

**Comment by Stiofan** [comment]
Hey thanks for the PR, we will review this tomorrow and hopefully get this merged.
Thanks :)

**Comment by MyThemeShop** [comment]
Hello @kprajapatii 

Added more code as requested.

Can you please check and confirm?

Thank you.

**Comment by kprajapatii** [comment]
@MyThemeShop Meta on archive pages looks fine now.

Thanks

**Comment by MyThemeShop** [comment]
Hello guys,

Once you release an update, can you please submit your product here with the essential details?
https://rankmath.com/contact/

We would like to add your plugin to our website:
https://rankmath.com/compatibility/

Thank you.

**Comment by Stiofan** [comment]
Will do, it should be released midweek, thanks!

**Pull request merged**
